# -*- coding: utf-8 -*-
"""Global Health Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEI-hYU59fyWsqxppdD7JT9IqnEhGEKs

# **GLOBAL HEALTH STATISTICS PROJECT (Health Analysis)**
"""

import pandas as pd

# Replace 'your_global_health_dataset.csv' with the actual path to your CSV file
df = pd.read_csv('Global Health Statistics.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

"""## **SECTION A: Exploratory Data Analysis**"""

display(df.describe())

df.info()

"""**Data Completeness**"""

missing_values = df.isnull().sum()
display(missing_values[missing_values > 0])

rows_with_missing_values = df[df.isnull().any(axis=1)]
display(rows_with_missing_values)

df_cleaned = df.dropna()

print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

df = df_cleaned.copy()

"""**Data Validity and Logic Checks**"""

# Filter the DataFrame to find records where 'Recovery Rate (%)' is greater than 100
invalid_recovery_rate_records = df[df['Recovery Rate (%)'] > 100]

# Display the found records
display(invalid_recovery_rate_records)

# Check for negative values in 'Mortality Rate (%)'
negative_mortality_rate = df[df['Mortality Rate (%)'] < 0]
display(f"Records with negative 'Mortality Rate (%):'", negative_mortality_rate)

# Check for negative values in 'Healthcare Access (%)'
negative_healthcare_access = df[df['Healthcare Access (%)'] < 0]
display(f"Records with negative 'Healthcare Access (%):'", negative_healthcare_access)

# Check for negative values in 'Doctors per 1000'
negative_doctors_per_1000 = df[df['Doctors per 1000'] < 0]
display(f"Records with negative 'Doctors per 1000:'", negative_doctors_per_1000)

# Check for negative values in 'Hospital Beds per 1000'
negative_hospital_beds_per_1000 = df[df['Hospital Beds per 1000'] < 0]
display(f"Records with negative 'Hospital Beds per 1000:'", negative_hospital_beds_per_1000)

# expected year range is 2000 - 2024
unexpected_years = df[(df['Year'] < 2000) | (df['Year'] > 2024)]

if not unexpected_years.empty:
    print("\nRecords with years outside the expected range (2000-2024):")
    display(unexpected_years)
else:
    print("\nNo records found with years outside the expected range (2000-2024).")

# Check for zero treatment costs
zero_cost_records = df[df['Average Treatment Cost (USD)'] == 0]
if not zero_cost_records.empty:
    print("\nRecords with zero 'Average Treatment Cost (USD)':")
    display(zero_cost_records)
else:
    print("\nNo records found with zero 'Average Treatment Cost (USD)'.")

# Check for unrealistically high treatment costs
# Let's consider costs above $100,000 as potentially 'unrealistically high' for this dataset's context.
high_cost_threshold = 70000 # Based on df.describe() max is 50000. Let's make an arbitrary high to be safe and find outliers.
unrealistically_high_cost_records = df[df['Average Treatment Cost (USD)'] > high_cost_threshold]

if not unrealistically_high_cost_records.empty:
    print(f"\nRecords with 'Average Treatment Cost (USD)' > ${high_cost_threshold:,}:")
    display(unrealistically_high_cost_records)
else:
    print(f"\nNo records found with 'Average Treatment Cost (USD)' above ${high_cost_threshold:,}.")

"""**Outliers Detection**

## Identify Treatment Cost Outliers
"""

Q1 = df['Average Treatment Cost (USD)'].quantile(0.25)
Q3 = df['Average Treatment Cost (USD)'].quantile(0.75)
IQR = Q3 - Q1

print(f"Q1: {Q1}")
print(f"Q3: {Q3}")
print(f"IQR: {IQR}")

upper_bound_extreme = Q3 + (3 * IQR)
lower_bound_extreme = Q1 - (3 * IQR)

print(f"Upper Bound for Extreme Outliers: {upper_bound_extreme}")
print(f"Lower Bound for Extreme Outliers: {lower_bound_extreme}")

treatment_cost_outliers = df[(df['Average Treatment Cost (USD)'] > upper_bound_extreme) | (df['Average Treatment Cost (USD)'] < lower_bound_extreme)]

print("\nExtreme Outliers in 'Average Treatment Cost (USD)':")
display(treatment_cost_outliers[['Disease Name', 'Average Treatment Cost (USD)']])

"""## Identify DALYs Outliers

"""

Q1_dalys = df['DALYs'].quantile(0.25)
Q3_dalys = df['DALYs'].quantile(0.75)
IQR_dalys = Q3_dalys - Q1_dalys

print(f"Q1 for DALYs: {Q1_dalys}")
print(f"Q3 for DALYs: {Q3_dalys}")
print(f"IQR for DALYs: {IQR_dalys}")

upper_bound_extreme_dalys = Q3_dalys + (3 * IQR_dalys)
lower_bound_extreme_dalys = Q1_dalys - (3 * IQR_dalys)

print(f"Upper Bound for Extreme DALYs Outliers: {upper_bound_extreme_dalys}")
print(f"Lower Bound for Extreme DALYs Outliers: {lower_bound_extreme_dalys}")

dalys_outliers = df[(df['DALYs'] > upper_bound_extreme_dalys) | (df['DALYs'] < lower_bound_extreme_dalys)]

print("\nExtreme Outliers in 'DALYs':")
display(dalys_outliers[['Country', 'DALYs']])

"""## Identify Mortality Rate Outliers

"""

Q1_mortality = df['Mortality Rate (%)'].quantile(0.25)
Q3_mortality = df['Mortality Rate (%)'].quantile(0.75)
IQR_mortality = Q3_mortality - Q1_mortality

print(f"Q1 for Mortality Rate (%): {Q1_mortality}")
print(f"Q3 for Mortality Rate (%): {Q3_mortality}")
print(f"IQR for Mortality Rate (%): {IQR_mortality}")

upper_bound_extreme_mortality = Q3_mortality + (3 * IQR_mortality)
lower_bound_extreme_mortality = Q1_mortality - (3 * IQR_mortality)

print(f"Upper Bound for Extreme Mortality Rate (%) Outliers: {upper_bound_extreme_mortality}")
print(f"Lower Bound for Extreme Mortality Rate (%) Outliers: {lower_bound_extreme_mortality}")

mortality_rate_outliers = df[(df['Mortality Rate (%)'] > upper_bound_extreme_mortality) | (df['Mortality Rate (%)'] < lower_bound_extreme_mortality)]

print("\nExtreme Outliers in 'Mortality Rate (%):'")
display(mortality_rate_outliers[['Country', 'Disease Category', 'Mortality Rate (%)']])

"""## Summary of Outlier Analysis

Based on the Interquartile Range (IQR) method (3 * IQR for extreme outliers):

- **Average Treatment Cost (USD)**: No extreme outliers were identified. This suggests that while there might be some variability, there are no data points that fall drastically outside the typical range as defined by the 3 * IQR rule.

- **DALYs (Disability-Adjusted Life Years)**: No extreme outliers were identified. This indicates that the DALYs values are relatively consistent across the dataset and do not contain any data points that are exceptionally high or low compared to the majority.

- **Mortality Rate (%)**: No extreme outliers were identified. Similar to the other metrics, the mortality rates appear to be within an expected distribution without extreme deviations.

In conclusion, the initial extreme outlier detection using the 3 * IQR rule did not find any data points that were considered extreme outliers for 'Average Treatment Cost (USD)', 'DALYs', or 'Mortality Rate (%)' in this dataset. The box plots visually confirm this by showing no individual data points beyond the computed extreme outlier bounds.

## **SECTION B: UNIVARIATE & DISTRIBUTION ANALYSIS**

**Disease & Population Overview**
"""

# Calculate the frequency of each disease category
disease_category_counts = df['Disease Category'].value_counts()

print("Most Frequent Disease Categories:")
display(disease_category_counts)

# Calculate the distribution of diseases across age groups
disease_age_group_distribution = df.groupby(['Age Group', 'Disease Category']).size().unstack(fill_value=0)

print("Distribution of Diseases Across Age Groups:")
display(disease_age_group_distribution)

# Calculate the proportion of records by gender
gender_proportion = df['Gender'].value_counts(normalize=True) * 100

print("Proportion of Records by Gender:")
display(gender_proportion)

"""**Health Metric Distributions**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Prevalence Rate (%)'], bins=30, kde=True)
plt.title('Distribution of Prevalence Rate (%) Globally')
plt.xlabel('Prevalence Rate (%)')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Mortality Rate (%)'], bins=30, kde=True)
plt.title('Distribution of Mortality Rate (%)')
plt.xlabel('Mortality Rate (%)')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Recovery Rate (%)'], bins=30, kde=True)
plt.title('Distribution of Recovery Rate (%)')
plt.xlabel('Recovery Rate (%)')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Average Treatment Cost (USD)'], bins=30, kde=True)
plt.title('Distribution of Average Treatment Cost (USD)')
plt.xlabel('Average Treatment Cost (USD)')
plt.ylabel('Frequency')
plt.show()

"""## **SECTION C: GEOGRAPHICAL HEALTH ANALYSIS**

**Country-Level Burden**
"""

# Calculate total DALYs per country
total_dalys_by_country = df.groupby('Country')['DALYs'].sum().sort_values(ascending=False)

print("Countries with the Highest Total Disease Burden (DALYs):")
display(total_dalys_by_country.head(10))

# Calculate average mortality rate per country
average_mortality_by_country = df.groupby('Country')['Mortality Rate (%)'].mean().sort_values(ascending=False)

print("\nCountries with the Highest Average Mortality Rates:")
display(average_mortality_by_country.head(10))

# Calculate average healthcare access per country (sorted ascending for lowest access)
average_healthcare_access_by_country = df.groupby('Country')['Healthcare Access (%)'].mean().sort_values(ascending=True)

print("\nCountries with the Lowest Average Healthcare Access:")
display(average_healthcare_access_by_country.head(10))

"""**Regional Inequality**

## Analyze Mortality Rate by Income Level
"""

df['Income_Bracket'] = pd.cut(df['Per Capita Income (USD)'],
                                   bins=[0, 10000, 30000, 60000, df['Per Capita Income (USD)'].max()],
                                   labels=['Low Income', 'Lower-Middle Income', 'Upper-Middle Income', 'High Income'],
                                   right=False)

print("DataFrame with new 'Income_Bracket' column:")
display(df.head())

average_mortality_by_income = df.groupby('Income_Bracket', observed=False)['Mortality Rate (%)'].mean().sort_values(ascending=False)

print("Average Mortality Rate (%) by Income Bracket:")
display(average_mortality_by_income)

high_income_countries_mortality = df[df['Income_Bracket'] == 'High Income']

print("Mortality Rates in High Income Countries (sorted by Per Capita Income):")
display(high_income_countries_mortality[['Country', 'Per Capita Income (USD)', 'Mortality Rate (%)']].sort_values(by='Per Capita Income (USD)', ascending=False).head(10))

Q1_prevalence = df['Prevalence Rate (%)'].quantile(0.25)
Q3_prevalence = df['Prevalence Rate (%)'].quantile(0.75)

Q1_mortality_rate = df['Mortality Rate (%)'].quantile(0.25)
Q3_mortality_rate = df['Mortality Rate (%)'].quantile(0.75)

print(f"Q1 for Prevalence Rate (%): {Q1_prevalence}")
print(f"Q3 for Prevalence Rate (%): {Q3_prevalence}")
print(f"Q1 for Mortality Rate (%): {Q1_mortality_rate}")
print(f"Q3 for Mortality Rate (%): {Q3_mortality_rate}")

high_prevalence_low_mortality_countries = df[(df['Prevalence Rate (%)'] > Q3_prevalence) & (df['Mortality Rate (%)'] < Q1_mortality_rate)]

print("Countries with High Prevalence Rate and Low Mortality Rate:")
display(high_prevalence_low_mortality_countries[['Country', 'Disease Name', 'Prevalence Rate (%)', 'Mortality Rate (%)']].drop_duplicates().head(10))

plt.figure(figsize=(10, 6))
sns.barplot(x=average_mortality_by_income.index, y=average_mortality_by_income.values, hue=average_mortality_by_income.index, palette='viridis', legend=False)
plt.title('Average Mortality Rate (%) by Income Bracket')
plt.xlabel('Income Bracket')
plt.ylabel('Average Mortality Rate (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Summary of Regional Inequality Analysis

### Mortality Rate Variation by Income Level

- The average mortality rate generally shows slight variations across different income brackets. From our analysis:
  - High Income: Approximately 5.07%
  - Upper-Middle Income: Approximately 5.06%
  - Low Income: Approximately 5.04%
  - Lower-Middle Income: Approximately 5.04%
- The bar chart visually confirms these minor differences, suggesting that while high-income countries have a slightly higher average mortality rate than lower-income countries in this dataset, the difference is not substantial. This might indicate that other factors besides per capita income are stronger determinants of mortality rates, or that the specific diseases covered in this dataset behave differently across income levels.

### Mortality in High-Income Countries

- When examining specific high-income countries (sorted by 'Per Capita Income (USD)'), we observe a range of mortality rates.
- For example, countries like Argentina and Mexico with very high 'Per Capita Income (USD)' entries show varying mortality rates (e.g., Argentina at 3.40% and Mexico at 2.04% for some entries, but also Brazil at 9.32% and UK at 5.24% at the higher end of income).
- This suggests that even within the 'High Income' bracket, there isn't a consistent trend of uniformly low mortality rates. Individual country-specific health policies, disease prevalence, and healthcare system efficiency likely play significant roles.

### Countries with High Prevalence and Low Mortality

- We identified several countries that exhibit high disease prevalence rates (above Q3 for prevalence) but relatively low mortality rates (below Q1 for mortality). These include:
  - Canada (Tuberculosis, Prevalence: 16.03%, Mortality: 0.39%)
  - Brazil (Ebola, Prevalence: 16.01%, Mortality: 1.35%)
  - Nigeria (Diabetes, Prevalence: 18.17%, Mortality: 2.12%)
  - France (Polio, Prevalence: 17.97%, Mortality: 0.51%)
  - China (Cancer, Prevalence: 18.82%, Mortality: 0.55%)
  - China (Hepatitis, Prevalence: 15.83%, Mortality: 2.06%)
  - Turkey (Hepatitis, Prevalence: 19.67%, Mortality: 0.46%)
- These countries or specific disease instances represent cases where effective treatment, prevention strategies, or simply the nature of the disease itself leads to a high number of affected individuals but a lower fatality rate. This is an important area for further investigation to understand successful health interventions.

## Summary:

### Q&A
1.  **How does the mortality rate vary across different income levels?**
    The average mortality rate shows only slight variations across different income brackets: High Income (approximately 5.07%), Upper-Middle Income (approximately 5.06%), Low Income (approximately 5.04%), and Lower-Middle Income (approximately 5.04%). This suggests that per capita income alone might not be a strong determinant of average mortality rates in this dataset.

2.  **Is there a consistent trend of lower mortality in high-income countries?**
    No, there is not a consistent trend of uniformly low mortality rates in high-income countries. While examining specific high-income countries, a range of mortality rates was observed. For example, Argentina showed 3.40% and Mexico 2.04%, but Brazil had 9.32% and the UK 5.24% for some entries among the highest per capita income countries.

3.  **Which countries exhibit high disease prevalence rates but relatively low mortality rates?**
    Several countries were identified with high prevalence rates (above the 75th percentile) and low mortality rates (below the 25th percentile). These include:
    *   Canada (Tuberculosis, Prevalence: 16.03%, Mortality: 0.39%)
    *   Brazil (Ebola, Prevalence: 16.01%, Mortality: 1.35%)
    *   Nigeria (Diabetes, Prevalence: 18.17%, Mortality: 2.12%)
    *   France (Polio, Prevalence: 17.97%, Mortality: 0.51%)
    *   China (Cancer, Prevalence: 18.82%, Mortality: 0.55%)
    *   China (Hepatitis, Prevalence: 15.83%, Mortality: 2.06%)
    *   Turkey (Hepatitis, Prevalence: 19.67%, Mortality: 0.46%)

### Data Analysis Key Findings
*   The average mortality rates across income brackets are remarkably similar, with High Income at approximately 5.07%, Upper-Middle Income at 5.06%, Low Income at 5.04%, and Lower-Middle Income at 5.04%.
*   Among high-income countries, there is significant variability in mortality rates, with examples like Argentina at 3.40% and Mexico at 2.04%, contrasting with Brazil at 9.32% and the UK at 5.24% for certain disease entries, indicating no consistent trend of uniformly low mortality.
*   Countries identified with high prevalence (above the 75th percentile) and low mortality (below the 25th percentile) include Canada (Tuberculosis, 16.03% prevalence, 0.39% mortality), Brazil (Ebola, 16.01% prevalence, 1.35% mortality), and China (Cancer, 18.82% prevalence, 0.55% mortality), among others.

### Insights or Next Steps
*   Income level alone appears to be a weak predictor of average mortality rates in this dataset, suggesting that other factors like specific diseases, healthcare policies, and intervention effectiveness play a more dominant role.
*   Further investigation into the countries exhibiting high prevalence and low mortality could provide valuable insights into successful public health interventions, effective treatment strategies, or unique disease characteristics that lead to better patient outcomes despite widespread infection.

## **SECTION D: TEMPORAL (TIME-SERIES) ANALYSIS**

**Trends Over Time**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate average global prevalence rate per year
global_prevalence_trend = df.groupby('Year')['Prevalence Rate (%)'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Year', y='Prevalence Rate (%)', data=global_prevalence_trend)
plt.title('Global Disease Prevalence Rate Over the Years')
plt.xlabel('Year')
plt.ylabel('Average Prevalence Rate (%)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(global_prevalence_trend['Year'].unique(), rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate average global mortality rate per year
global_mortality_trend = df.groupby('Year')['Mortality Rate (%)'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Year', y='Mortality Rate (%)', data=global_mortality_trend, color='red')
plt.title('Global Mortality Rate Over the Years')
plt.xlabel('Year')
plt.ylabel('Average Mortality Rate (%)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(global_mortality_trend['Year'].unique(), rotation=45)
plt.tight_layout()
plt.show()

# Calculate the average 'Improvement in 5 Years (%)' per disease category
disease_improvement = df.groupby('Disease Category')['Improvement in 5 Years (%)'].mean().sort_values(ascending=False)

print("Disease Categories with the Strongest Average Improvement Over 5 Years:")
display(disease_improvement.head(10))

"""**Disease-Specific Trends**

## Identify Diseases with Greatest Mortality Reduction
"""

disease_mortality_trends = df.groupby(['Disease Name', 'Year'])['Mortality Rate (%)'].mean().reset_index()

disease_mortality_reduction = []

for disease_name in disease_mortality_trends['Disease Name'].unique():
    disease_data = disease_mortality_trends[disease_mortality_trends['Disease Name'] == disease_name]

    if len(disease_data) > 1: # Only consider diseases with data for more than one year
        earliest_year_data = disease_data.sort_values(by='Year').iloc[0]
        latest_year_data = disease_data.sort_values(by='Year').iloc[-1]

        earliest_mortality = earliest_year_data['Mortality Rate (%)']
        latest_mortality = latest_year_data['Mortality Rate (%)']

        mortality_reduction = earliest_mortality - latest_mortality

        disease_mortality_reduction.append({
            'Disease Name': disease_name,
            'Earliest Year Mortality (%)': earliest_mortality,
            'Latest Year Mortality (%)': latest_mortality,
            'Mortality Reduction (%)': mortality_reduction
        })

df_mortality_reduction = pd.DataFrame(disease_mortality_reduction)

print("Mortality Reduction Calculation for Each Disease (first 10 rows):")
display(df_mortality_reduction.head(10))

top_10_reductions = df_mortality_reduction.sort_values(by='Mortality Reduction (%)', ascending=False).head(10)

print("Top 10 Diseases with Greatest Mortality Reduction (%):")
display(top_10_reductions)

"""## Identify Diseases with Little or No Improvement"""

diseases_little_no_improvement = df[df['Improvement in 5 Years (%)'] <= 0.5]

diseases_little_no_improvement = diseases_little_no_improvement[['Disease Name', 'Improvement in 5 Years (%)']].drop_duplicates()

diseases_little_no_improvement_sorted = diseases_little_no_improvement.sort_values(by='Improvement in 5 Years (%)', ascending=True)

print("Diseases with Little or No Improvement (Top 10):")
display(diseases_little_no_improvement_sorted.head(10))

"""## Analyze Improvement Consistency Across Countries

"""

average_improvement_by_country = df.groupby('Country')['Improvement in 5 Years (%)'].mean().reset_index()

print("Countries with the Highest Average Improvement Over 5 Years:")
display(average_improvement_by_country.sort_values(by='Improvement in 5 Years (%)', ascending=False).head(10))

print("\nCountries with the Lowest Average Improvement Over 5 Years:")
display(average_improvement_by_country.sort_values(by='Improvement in 5 Years (%)', ascending=True).head(10))

"""## Visualize Disease-Specific Trends and Improvements

"""

selected_diseases_for_mortality_trend = top_10_reductions['Disease Name'].head(5).tolist()

mortality_trend_data = df[df['Disease Name'].isin(selected_diseases_for_mortality_trend)].groupby(['Disease Name', 'Year'])['Mortality Rate (%)'].mean().reset_index()

print("Data for selected diseases' mortality trends:")
display(mortality_trend_data.head())

plt.figure(figsize=(14, 7))
sns.lineplot(data=mortality_trend_data, x='Year', y='Mortality Rate (%)', hue='Disease Name', marker='o')
plt.title('Mortality Rate (%) Trend Over Years for Selected Diseases')
plt.xlabel('Year')
plt.ylabel('Average Mortality Rate (%)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(mortality_trend_data['Year'].unique(), rotation=45)
plt.legend(title='Disease Name', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""## Summary:

### Q&A

1.  **Which diseases showed the greatest reduction in mortality?**
    The top 5 diseases with the greatest mortality reduction were Cancer (0.388%), Alzheimer's Disease (0.367%), Malaria (0.316%), Diabetes (0.278%), and Tuberculosis (0.263%).

2.  **Which diseases showed little or no improvement based on the 'Improvement in 5 Years (%)' metric?**
    Diseases showing 0.0% improvement in 5 years include Parkinson's Disease, Leprosy, Ebola, Rabies, Diabetes, Hypertension, Malaria, Hepatitis, Polio, and Alzheimer's Disease.

3.  **Are healthcare improvements consistent across all countries or concentrated in a few?**
    Healthcare improvements, as measured by the 'Improvement in 5 Years (%)' metric, appear to be relatively consistent across the analyzed countries. The average improvement rates ranged narrowly from approximately 4.938% (UK) to 5.078% (Canada), suggesting a widespread rather than concentrated distribution of improvements.

### Data Analysis Key Findings

*   **Greatest Mortality Reduction:** Cancer showed the highest mortality reduction at 0.388%, followed by Alzheimer's Disease (0.367%) and Malaria (0.316%).
*   **Diseases with Little to No Improvement:** Ten diseases, including Parkinson's Disease, Ebola, and Diabetes, registered 0.0% improvement in 5 years, indicating no progress in mortality reduction over that period.
*   **Consistency of Improvements Across Countries:** The average 'Improvement in 5 Years (%)' across countries showed a narrow range (from 4.938% to 5.078%), with Canada having the highest average improvement (5.078%) and the UK the lowest (4.938%). This suggests a relatively uniform rate of improvement across all countries.
*   **Visualizations:** Line plots effectively displayed the declining mortality rate trends for top diseases like Cancer and Alzheimer's Disease, while bar charts illustrated the 0.0% improvement for diseases with little to no progress.

### Insights or Next Steps

*   Further investigation is needed into diseases showing 0.0% 'Improvement in 5 Years (%)' to understand the underlying causes of stagnation and identify potential interventions.
*   While overall improvements are consistent across countries, a deeper dive into country-specific disease burdens and interventions could reveal best practices or areas needing targeted support.

## **SECTION E: DISEASE BURDEN & IMPACT ANALYSIS**

**DALYs & Impact**
"""

# Calculate total DALYs per disease to find those contributing the most
disease_dalys_contribution = df.groupby('Disease Name')['DALYs'].sum().sort_values(ascending=False)

print("Diseases with the Highest Total DALYs Contribution:")
display(disease_dalys_contribution.head(10))

# Define 'low mortality' as below the 25th percentile (Q1) of Mortality Rate (%)
# Define 'very high DALYs' as above the 75th percentile (Q3) of DALYs
Q1_mortality = df['Mortality Rate (%)'].quantile(0.25)
Q3_dalys = df['DALYs'].quantile(0.75)

low_mortality_high_dalys_diseases = df[(df['Mortality Rate (%)'] < Q1_mortality) &
                                       (df['DALYs'] > Q3_dalys)]

print("Diseases with Low Mortality Rate but Very High DALYs:")
display(low_mortality_high_dalys_diseases[['Disease Name', 'Mortality Rate (%)', 'DALYs', 'Country']].drop_duplicates().head(10))

# Calculate the average DALYs per age group to see how disease burden differs
disease_burden_by_age_group = df.groupby('Age Group')['DALYs'].mean().sort_values(ascending=False)

print("Average Disease Burden (DALYs) Across Age Groups:")
display(disease_burden_by_age_group)

"""**Disease Category Comparison**

## Calculate Average DALYs by Disease Category
"""

average_dalys_by_disease_category = df.groupby('Disease Category')['DALYs'].mean().sort_values(ascending=False)

print("Average DALYs by Disease Category:")
display(average_dalys_by_disease_category)

print("\nDisease Category with the Highest Average DALYs:")
display(average_dalys_by_disease_category.head(1))

"""## Categorize Diseases as Communicable/Non-Communicable


"""

disease_type_mapping = {
    'Malaria': 'Communicable',
    'Ebola': 'Communicable',
    'COVID-19': 'Communicable',
    'Tuberculosis': 'Communicable',
    'Hepatitis': 'Communicable',
    'Polio': 'Communicable',
    'HIV/AIDS': 'Communicable',
    'Influenza': 'Communicable',
    'Cholera': 'Communicable',
    'Dengue': 'Communicable',
    'Measles': 'Communicable',
    'Rabies': 'Communicable',
    'Tetanus': 'Communicable',
    'Typhoid': 'Communicable',
    'Zika': 'Communicable',
    'Lyme Disease': 'Communicable',
    'West Nile Virus': 'Communicable',
    'Zoonotic Diseases': 'Communicable',
    'Smallpox': 'Communicable',
    'Syphilis': 'Communicable',
    'Gonorrhea': 'Communicable',
    'Chlamydia': 'Communicable',
    'Herpes': 'Communicable',
    'Diphtheria': 'Communicable',
    'Pertussis': 'Communicable',
    'Mumps': 'Communicable',
    'Rubella': 'Communicable',
    'Varicella': 'Communicable',
    'Yellow Fever': 'Communicable',
    'Leptospirosis': 'Communicable',
    'Chagas Disease': 'Communicable',
    'Leishmaniasis': 'Communicable',
    'Schistosomiasis': 'Communicable',
    'Filariasis': 'Communicable',
    'Onchocerciasis': 'Communicable',
    'Trachoma': 'Communicable',
    'Leprosy': 'Communicable',
    'African Trypanosomiasis': 'Communicable',
    'Echinococcosis': 'Communicable',
    'Cysticercosis': 'Communicable',
    'Dracunculiasis': 'Communicable',
    'Giardiasis': 'Communicable',
    'Cryptosporidiosis': 'Communicable',
    'Amoebiasis': 'Communicable',
    'Rotavirus': 'Communicable',
    'Norovirus': 'Communicable',

    'Parkinson\'s Disease': 'Non-Communicable',
    'Diabetes': 'Non-Communicable',
    'Cancer': 'Non-Communicable',
    'Cardiovascular Disease': 'Non-Communicable',
    'Alzheimer\'s Disease': 'Non-Communicable',
    'Hypertension': 'Non-Communicable',
    'Stroke': 'Non-Communicable',
    'Chronic Obstructive Pulmonary Disease': 'Non-Communicable',
    'Asthma': 'Non-Communicable',
    'Kidney Disease': 'Non-Communicable',
    'Osteoporosis': 'Non-Communicable',
    'Arthritis': 'Non-Communicable',
    'Obesity': 'Non-Communicable',
    'Mental Health Disorders': 'Non-Communicable',
    'Depression': 'Non-Communicable',
    'Anxiety Disorders': 'Non-Communicable',
    'Bipolar Disorder': 'Non-Communicable',
    'Schizophrenia': 'Non-Communicable',
    'Epilepsy': 'Non-Communicable',
    'Multiple Sclerosis': 'Non-Communicable',
    'Dementia': 'Non-Communicable',
    'Cirrhosis': 'Non-Communicable',
    'Gallstones': 'Non-Communicable',
    'Psoriasis': 'Non-Communicable',
    'Eczema': 'Non-Communicable',
    'Glaucoma': 'Non-Communicable',
    'Cataracts': 'Non-Communicable',
    'Macular Degeneration': 'Non-Communicable',
    'Hearing Loss': 'Non-Communicable',
    'Dental Caries': 'Non-Communicable',
    'Periodontal Disease': 'Non-Communicable',
    'Autoimmune Disease': 'Non-Communicable',
    'Lupus': 'Non-Communicable',
    'Rheumatoid Arthritis': 'Non-Communicable',
    'Type 1 Diabetes': 'Non-Communicable',
    'Celiac Disease': 'Non-Communicable',
    'Crohn\'s Disease': 'Non-Communicable',
    'Ulcerative Colitis': 'Non-Communicable',
    'Thyroid Disorders': 'Non-Communicable',
    'Anemia': 'Non-Communicable',
    'Migraine': 'Non-Communicable'
}

print("Disease type mapping dictionary created.")

df['Disease_Type'] = df['Disease Name'].map(disease_type_mapping).fillna('Non-Communicable')

print("DataFrame with new 'Disease_Type' column (first 5 rows):")
display(df[['Disease Name', 'Disease Category', 'Disease_Type']].head())

"""## Compare Burden of Communicable vs. Non-Communicable Diseases"""

disease_type_burden = df.groupby('Disease_Type')[['DALYs', 'Mortality Rate (%)']].mean()

print("Average DALYs and Mortality Rate (%) by Disease Type:")
display(disease_type_burden)

"""## Visualize Disease Category Comparisons

"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1) Average Mortality Rate (%) by Disease Category
plt.figure(figsize=(12, 6))
sns.barplot(x=average_mortality_by_disease_category.index, y=average_mortality_by_disease_category.values, palette='viridis')
plt.title('Average Mortality Rate (%) by Disease Category')
plt.xlabel('Disease Category')
plt.ylabel('Average Mortality Rate (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 2) Average DALYs by Disease Category
plt.figure(figsize=(12, 6))
sns.barplot(x=average_dalys_by_disease_category.index, y=average_dalys_by_disease_category.values, palette='plasma')
plt.title('Average DALYs by Disease Category')
plt.xlabel('Disease Category')
plt.ylabel('Average DALYs')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 3) Comparison of DALYs and Mortality Rates between Communicable and Non-Communicable Diseases
disease_type_burden_melted = disease_type_burden.reset_index().melt('Disease_Type', var_name='Metric', value_name='Average Value')

plt.figure(figsize=(10, 6))
sns.barplot(x='Disease_Type', y='Average Value', hue='Metric', data=disease_type_burden_melted, palette='muted')
plt.title('Average DALYs and Mortality Rate (%) by Disease Type')
plt.xlabel('Disease Type')
plt.ylabel('Average Value')
plt.legend(title='Metric')
plt.tight_layout()
plt.show()

"""## Summary:

### Q&A
1.  **Which disease category has the highest average mortality rate?**
    The 'Bacterial' disease category has the highest average mortality rate at 5.08%.
2.  **Which disease category has the highest long-term disability impact (DALYs)?**
    The 'Autoimmune' disease category has the highest average DALYs at 2525.66.
3.  **How do communicable and non-communicable diseases compare in terms of burden?**
    Communicable diseases have an average DALYs of 2504.19 and an average mortality rate of 5.06%. Non-communicable diseases have a slightly higher average DALYs of 2505.49 but a slightly lower average mortality rate of 5.03%. Overall, both types contribute very similarly to the disease burden.

### Data Analysis Key Findings
*   The 'Bacterial' disease category recorded the highest average mortality rate among all categories at 5.08019%.
*   The 'Autoimmune' disease category exhibited the highest average DALYs, with a value of 2525.659439, indicating the highest long-term disability impact.
*   When comparing disease types, communicable diseases showed an average DALYs of 2504.19 and an average mortality rate of 5.06%.
*   Non-communicable diseases had a slightly higher average DALYs of 2505.49 but a slightly lower average mortality rate of 5.03%. The difference in average burden between the two types is minimal.
*   All diseases were successfully classified as either 'Communicable' or 'Non-Communicable' based on a predefined mapping, with unmapped diseases defaulting to 'Non-Communicable'.
*   Visualizations effectively illustrated the average mortality rate and DALYs by disease category, as well as the comparative burden between communicable and non-communicable diseases.

### Insights or Next Steps
*   Despite different specific categories leading in mortality and DALYs, the overall disease burden, when broadly categorized into communicable and non-communicable, shows striking similarity in average DALYs and mortality rates. This suggests that public health strategies should maintain a balanced focus across both types of diseases.
*   Further investigation into the specific diseases within the 'Bacterial' and 'Autoimmune' categories could provide more granular insights into the primary drivers of high mortality and long-term disability, respectively, allowing for more targeted intervention development.

## Generate README.md Content

```markdown
# Global Health Statistics Project (Health Analysis) - README

## Project Objective

The primary objective of this project is to perform a comprehensive health analysis using global health statistics. This involves exploring various aspects of disease prevalence, mortality, healthcare access, and their socio-economic and temporal trends across different countries and disease categories.

## Dataset Details

The analysis is based on the **'Global Health Statistics.csv'** dataset, which contains detailed information on various health metrics, diseases, and socio-economic indicators across multiple countries and years.
```

```markdown
## Methodologies Used

### Data Cleaning and Preprocessing

Initial data completeness checks revealed a single row with missing values across several columns (`Hospital Beds per 1000`, `Treatment Type`, `Average Treatment Cost (USD)`, `Availability of Vaccines/Treatment`, `Recovery Rate (%)`, `DALYs`, `Improvement in 5 Years (%)`, `Per Capita Income (USD)`, `Education Index`, `Urbanization Rate (%)`). This row was dropped to ensure data integrity for subsequent analysis, reducing the dataset size from 70217 to 70216 entries.

### Data Validity and Logic Checks

Several logical checks were performed to ensure data validity:
- No records were found where 'Recovery Rate (%)' was greater than 100.
- No records were found with negative values for 'Mortality Rate (%)', 'Healthcare Access (%)', 'Doctors per 1000', or 'Hospital Beds per 1000'.
- All 'Year' entries were within the expected range of 2000-2024.
- No records showed zero or unrealistically high 'Average Treatment Cost (USD)' (e.g., above $70,000).

### Outlier Detection

Outlier analysis was conducted using the Interquartile Range (IQR) method (specifically, 3 * IQR for extreme outliers) for key numerical features:
- **Average Treatment Cost (USD)**: No extreme outliers were identified.
- **DALYs (Disability-Adjusted Life Years)**: No extreme outliers were identified.
- **Mortality Rate (%)**: No extreme outliers were identified.

This indicates that the dataset is relatively clean and does not contain data points that fall drastically outside the typical range for these critical metrics.
```

```markdown
## Univariate & Distribution Analysis

### Disease & Population Overview
- The frequency of different **Disease Categories** was analyzed to identify the most common types of diseases in the dataset.
- The distribution of diseases across various **Age Groups** and the **proportion of records by Gender** were examined to understand demographic patterns in health data.

### Health Metric Distributions
- Histograms were generated to visualize the distribution of key health metrics:
    - **Prevalence Rate (%)**: Showed the frequency distribution of disease occurrence.
    - **Mortality Rate (%)**: Illustrated the spread of fatality rates across the dataset.
    - **Recovery Rate (%)**: Presented the distribution of patient recovery success.
    - **Average Treatment Cost (USD)**: Displayed the distribution of treatment expenses.
These visualizations provide insights into the central tendency, spread, and shape of these critical health indicators.
```

```markdown
## Geographical Health Analysis

### Country-Level Burden
- **Highest Total DALYs**: Identified countries with the highest total Disease-Adjusted Life Years, indicating the greatest overall disease burden.
- **Highest Average Mortality Rates**: Pinpointed countries experiencing the highest average mortality rates.
- **Lowest Average Healthcare Access**: Highlighted countries with the lowest average healthcare access, suggesting potential disparities in health infrastructure.

### Regional Inequality
- **Mortality Rate Variation by Income Level**: Analysis showed only slight variations in average mortality rates across different income brackets (High, Upper-Middle, Low, Lower-Middle Income), suggesting that per capita income alone might not be a strong determinant of average mortality rates in this dataset.
- **Mortality in High-Income Countries**: No consistent trend of uniformly low mortality rates was observed in high-income countries. Specific high-income nations showed a range of mortality rates, implying that individual country-specific health policies and disease prevalence play significant roles.
- **Countries with High Prevalence and Low Mortality**: Several countries were identified with high disease prevalence rates (above Q3) but relatively low mortality rates (below Q1). Examples include Canada (Tuberculosis), Brazil (Ebola), Nigeria (Diabetes), France (Polio), China (Cancer, Hepatitis), and Turkey (Hepatitis). These cases suggest effective treatment, prevention strategies, or the nature of the diseases themselves lead to lower fatality despite widespread occurrence.
- **Visualizations**: Bar charts displayed average mortality rates by income bracket, and scatter plots illustrated the relationship between prevalence and mortality rates, colored by income bracket, confirming a general distribution rather than clear clusters for income levels.
```

```markdown
## Temporal (Time-Series) Analysis

### Trends Over Time
- **Global Prevalence Rate**: A line plot showed the trend of the average global prevalence rate over the years.
- **Global Mortality Rate**: A line plot displayed the trend of the average global mortality rate over the years, revealing overall patterns of increase or decrease.
- **Disease Category Improvement**: The average 'Improvement in 5 Years (%)' was calculated for each disease category, identifying those with the strongest average improvement (e.g., 'Bacterial' diseases showing the highest average improvement).

### Disease-Specific Trends
- **Greatest Mortality Reduction**: Diseases with the most significant mortality reduction were identified by comparing their average mortality rates in the earliest and latest years. Top diseases included Cancer, Alzheimer's Disease, Malaria, Diabetes, and Tuberculosis, showing reductions ranging from 0.388% to 0.263%.
- **Little or No Improvement**: Diseases showing 'Improvement in 5 Years (%)' values less than or equal to 0.5% were identified as having little to no progress. This included Parkinson's Disease, Leprosy, Ebola, Rabies, Diabetes, Hypertension, Malaria, Hepatitis, Polio, and Alzheimer's Disease, all registering 0.0% improvement in 5 years.
- **Consistency of Improvements Across Countries**: Analysis of the average 'Improvement in 5 Years (%)' by country indicated that healthcare improvements are relatively consistent across countries. The average improvement rates ranged narrowly from approximately 4.938% (UK) to 5.078% (Canada), suggesting a widespread rather than concentrated distribution of improvements.
- **Visualizations**: Line plots illustrated the mortality rate trends for selected diseases with significant reduction, and bar charts displayed the improvement rates for diseases showing little to no progress.
```

```markdown
## Disease Burden & Impact Analysis

### DALYs & Impact
- **Highest Total DALYs Contribution**: Diseases like Parkinson's Disease, Tuberculosis, and Malaria were identified as having the highest total DALYs, indicating their significant long-term impact on health and productivity.
- **Low Mortality Rate but Very High DALYs**: Several diseases were found to have low mortality rates (below Q1) but very high DALYs (above Q3), such as HIV/AIDS (e.g., in France, 0.44% mortality, 3757 DALYs) and various diseases across different countries, suggesting conditions that cause chronic disability rather than immediate fatality.
- **Average DALYs Across Age Groups**: Analysis showed how disease burden (DALYs) differs across age groups, providing insights into which populations are most affected by long-term health issues.

### Disease Category Comparison
- **Average DALYs by Disease Category**: 'Autoimmune' disease category exhibited the highest average DALYs (2525.66), indicating the highest long-term disability impact among categories.
- **Communicable vs. Non-Communicable Diseases**: After classifying diseases into 'Communicable' and 'Non-Communicable' types:
    - **Communicable diseases** had an average DALYs of 2504.19 and an average mortality rate of 5.06%.
    - **Non-Communicable diseases** had a slightly higher average DALYs of 2505.49 but a slightly lower average mortality rate of 5.03%.
    - This suggests a very similar overall burden between the two broad categories.
- **Visualizations**: Bar charts were used to compare average mortality rates and DALYs by disease category, as well as to highlight the burden comparison between communicable and non-communicable diseases.
```

```markdown
## Disease Burden & Impact Analysis

### DALYs & Impact
- **Highest Total DALYs Contribution**: Diseases like Parkinson's Disease, Tuberculosis, and Malaria were identified as having the highest total DALYs, indicating their significant long-term impact on health and productivity.
- **Low Mortality Rate but Very High DALYs**: Several diseases were found to have low mortality rates (below Q1) but very high DALYs (above Q3), such as HIV/AIDS (e.g., in France, 0.44% mortality, 3757 DALYs) and various diseases across different countries, suggesting conditions that cause chronic disability rather than immediate fatality.
- **Average DALYs Across Age Groups**: Analysis showed how disease burden (DALYs) differs across age groups, providing insights into which populations are most affected by long-term health issues.

### Disease Category Comparison
- **Average DALYs by Disease Category**: 'Autoimmune' disease category exhibited the highest average DALYs (2525.66), indicating the highest long-term disability impact among categories.
- **Communicable vs. Non-Communicable Diseases**: After classifying diseases into 'Communicable' and 'Non-Communicable' types:
    - **Communicable diseases** had an average DALYs of 2504.19 and an average mortality rate of 5.06%.
    - **Non-Communicable diseases** had a slightly higher average DALYs of 2505.49 but a slightly lower average mortality rate of 5.03%.
    - This suggests a very similar overall burden between the two broad categories.
- **Visualizations**: Bar charts were used to compare average mortality rates and DALYs by disease category, as well as to highlight the burden comparison between communicable and non-communicable diseases.
```

## Final Task

### Subtask:
Provide the complete README.md content as a markdown block, ready to be copied and pasted into a GitHub repository.

## Summary:

### Data Analysis Key Findings

*   **Data Integrity:** The initial dataset, comprising 70,217 entries, was cleaned by removing one row with missing values, resulting in 70,216 valid entries. Data validity checks confirmed no illogical values (e.g., recovery rates > 100% or negative health metrics) and no extreme outliers were found for 'Average Treatment Cost (USD)', 'DALYs', or 'Mortality Rate (%)'.
*   **Geographical Disparities:** Analysis identified countries with the highest total Disability-Adjusted Life Years (DALYs), highest average mortality rates, and lowest average healthcare access. There were only slight variations in average mortality rates across different income brackets, and high-income countries did not consistently show uniformly low mortality rates.
*   **Effective Management Cases:** Several countries were found to have high disease prevalence rates (above Q3) but relatively low mortality rates (below Q1), such as Canada (Tuberculosis), Brazil (Ebola), Nigeria (Diabetes), France (Polio), China (Cancer, Hepatitis), and Turkey (Hepatitis). This suggests effective treatment or prevention strategies are in place for these specific diseases in those regions.
*   **Temporal Trends & Improvements:**
    *   'Bacterial' diseases exhibited the highest average improvement in 5 years.
    *   Significant mortality reductions were observed for diseases like Cancer, Alzheimer's Disease, Malaria, Diabetes, and Tuberculosis, with reductions ranging from 0.263% to 0.388%.
    *   However, diseases such as Parkinson's Disease, Leprosy, Ebola, and Rabies showed little to no improvement (0.0% improvement in 5 years).
    *   Average healthcare improvements were found to be relatively consistent across countries, with average improvement rates ranging narrowly from approximately 4.938% (UK) to 5.078% (Canada).
*   **Disease Burden:**
    *   Parkinson's Disease, Tuberculosis, and Malaria contributed to the highest total DALYs.
    *   Diseases like HIV/AIDS (e.g., 0.44% mortality, 3757 DALYs in France) and others demonstrated low mortality rates but very high DALYs, indicating a significant long-term impact through chronic disability rather than immediate fatality.
    *   The 'Autoimmune' disease category showed the highest average DALYs (2525.66).
    *   Communicable diseases had an average DALYs of 2504.19 and an average mortality rate of 5.06%, while non-communicable diseases had a slightly higher average DALYs (2505.49) but a slightly lower average mortality rate (5.03%), suggesting a very similar overall burden between the two categories.

### Insights or Next Steps

*   **Targeted Interventions:** Investigate the specific healthcare policies, treatment protocols, or socio-economic factors in countries with high disease prevalence but low mortality to understand and replicate their success in other regions facing similar challenges.
*   **Focus on Chronic Disability:** Given the significant DALYs contribution from diseases with low mortality, future analysis should delve deeper into the long-term care needs, economic impact, and quality of life implications associated with these conditions to develop targeted support systems.
"""